version: '2'

services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.8-management'
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      # - RABBITMQ_USERNAME=test
      # - RABBITMQ_PASSWORD=test
    # volumes:
      # - ./rabbit_config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./rabbit_config/rabbitdata:/var/lib/rabbitmq
      # - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json
    ports:
    - 15682:15672
    - 5682:5672
